# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
highlighter:      rouge
gems:             [jekyll-paginate,kramdown,rouge]

# Permalinks
permalink:        pretty

# Setup
title:            A Hungry Developer
tagline:          ... literally and figuratively
url:              
paginate:         1
baseurl:          /
author:
  name:           Pamela Lu
  url:            http://no-namer-me.tumblr.com
  email:          pamlesleylu@yahoo.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/pamlesleylu
